{% set name = "ringspy" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9f3de072d614d51508f128219a539b388229b58c28a8cb23e6677de7ffb9b59f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - setuptools
    - wheel
    - requests >=2
    - numpy
    - scipy
    - matplotlib-base >=3.2.2
    - hexalattice
    - vtk

test:
  imports:
    - ringspy
  requires:
    - pip

  commands:
    - pip check

about:
  home: https://github.com/kingyin3613/ringspy
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE
  summary: A geometric generation tool for prismatic cellular solids
  doc_url: https://github.com/kingyin3613/ringspy/wiki
  dev_url: https://github.com/kingyin3613/ringspy

extra:
  recipe-maintainers:
    - kingyin3613
