{% set name = "ringspy" %}
{% set version = "0.4.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: e9e486c0c812848e20e17127c019e66d63160bfa7b519f38e9ccd71e54e152a6

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - setuptools
    - wheel
    - requests >=2
    - numpy
    - scipy
    - matplotlib-base >=3.2.2
    - hexalattice
    - vtk
    
test:
  imports:
    - ringspy
  requires:
    - pip

  commands:
    - pip check
    
about:
  home: https://github.com/kingyin3613/ringspy
  license: "GPL-3.0-or-later"
  license_family: GPL3
  license_file: LICENSE
  summary: "A geometric generation tool for prismatic cellular solids"
  doc_url: https://github.com/kingyin3613/ringspy/wiki
  dev_url: https://github.com/kingyin3613/ringspy

extra:
  recipe-maintainers:
    - kingyin3613
